### ISSUE TITLE
Some error messages are a bit noisy

### ISSUE THREAD

**Issue by FredTheDino** [sylt-lang/sylt-lang#186]
If you get some kind of syntax error - a lot of warnings come one after another.

This is often due to outer statements being wrong.

**Comment by FredTheDino** [comment]
Don't know what we can do to solve this - closing tomarrow unless someone has any ideas.

**Comment by FredTheDino** [comment]
@sornas had an idea about filtering out errors with the same tokens - might be a good first step.

**Comment by FredTheDino** [comment]
I had some ideas about taking the error message that has gone the furthest when we parse a structure - and them removing the others.
No idea how this would work - or if it's a good idea.

**Comment by EMattfolk** [comment]
This is mostly fixed now right? I feel like there is no point keeping this issue around.
