### ISSUE TITLE
Document the language

### ISSUE THREAD

**Issue by FredTheDino** [sylt-lang/sylt-lang#196]
The syntax, now that it's pretty nailed down, needs some form of documentation.

- [x] #418
- [x] #420
- [x] #421
- [x] #423
- [x] #442
- [x] #443
- [ ] #445

Minor bugs:

- [x] #449

**Comment by FredTheDino** [comment]
I want to wait with this until we have a more stable language. If there's one thing I dislike more than writing documentation - it's updating documentation.

**Comment by sornas** [comment]
Alternatives discussed:

- https://asciidoctor.org/
- https://github.com/rust-lang/mdBook

**Comment by sornas** [comment]
Also, we (at least me) are starting to feel more confident in the language stability.
