### ISSUE TITLE
Fix language ambiguities

### ISSUE THREAD

**Issue by FredTheDino** [sylt-lang/sylt-lang#271]
See #253

Initalizer lists and Dicts look the same - this isn't really a problem right now. But it might turn into one.

**Comment by EMattfolk** [comment]
To fix this, we should probably change the blob syntax to be something like:
```
A { .a = 1, .b = 2 }
```

**Comment by FredTheDino** [comment]
I kinda want the ` { .a = 1 }` - but I don't know if it's the best one. Should we change the blob syntax as well then? Do we want something like:
```
A :: blob {
  .a: int
}

a = A { .a = 1 }
```

Alternatively we can shamelessly steal Lua's syntax:
```
A :: blob {
  a: int
}

a = A { a = 1 }
```

I want them to be consistent - both of these solve the ambiguities.

**Comment by sornas** [comment]
Of these two, I prefer the second. That is also the same as Erik's comment above.

**Comment by FredTheDino** [comment]
> Of these two, I prefer the second. That is also the same as Erik's comment above.

This is unfortunate - but quite funny. Do you mean with or without the dot?

**Comment by sornas** [comment]
ah, dunno what happened there. i prefer without the dots.

**Comment by FredTheDino** [comment]
These are largely solved. Closing since I don't know of any more.
