### ISSUE TITLE
Default value in blob declaration?

### ISSUE THREAD

**Issue by sornas** [sylt-lang/sylt-lang#307]
```
A :: blob {
    a: float = 0.0,
    b: str,
    c: int? = nil,
}

start :: fn {
    A {
        b: "foo"
    } // ok
    A {
        a: 1.0,
    } // not ok, missing 'b'
}
```
Open questions:
- Referring to other values on the struct. Probably not allowed for normal fields, but what about functions if we add a way for `self`?

**Comment by FredTheDino** [comment]
Might result in unclear cases if the type syntax is changed. With anonymous blob instances:
```
player := { pos = (0, 0), player_num = 0 }
```
