### ISSUE TITLE
Function fields on blob auto-capture self?

### ISSUE THREAD

**Issue by sornas** [sylt-lang/sylt-lang#308]
It's a bit tiring to always have to write

```
self: !A = nil
self = A {
    answer: 42,
    f: fn -> int {
        self.answer
    },
}
self
```

**Comment by FredTheDino** [comment]
```
self := A {
    answer: 42,
    f: fn -> int {
		self.answer
	},
}
self
```
Self refers to the closest parent blob instance.

**Comment by EMattfolk** [comment]
After some late night discussions and 8 hours of sleep here is the summary:

This feature is possible to implement at a ~15% blob creation time loss. It would also come with another quirk. Some programs should be possible but will not be, e.g.

```
A :: blob {
    a: int,
    f: fn -> int,
}
start :: fn do
    A {
        a: 1,
        f: fn ->
            fn -> int do self.a end
        end()
    }
end
```
Basically `self` cannot be used except in methods, though the example demonstrates a method that is not possible. Now, we had an idea about using the dependency checker to solve this, but just allowing basic methods is the easier alternative.
It should be noted that there are similar programs that are not allowed by the dependency checker that should be. We conjectured that these "invalid" programs are rare and that there are workarounds in that case.

There were some other alternatives but they had similar problems. What do you think @sornas ?
