### ISSUE TITLE
Some issue with generics

### ISSUE THREAD

**Issue by EMattfolk** [sylt-lang/sylt-lang#427]
This causes some weird generics error.
```
start :: fn do
    [1, 2, 3] -> map(fn n: int -> int do n * n end) -> for_each(fn n: int do print(n) end)
end
```

```
typecheck error: /home/erik/Documents/sylt-lang/t.sy:2
      Got '#OUT', which it cannot be
      Generics are not supported as arguments - only parameters
   1 | start :: fn do
   2 |     [1, 2, 3] -> map(fn n: int -> int do n * n end) -> for_each(fn n: int do print(n) end)
                                                                                                 ^
  ```

**Comment by EMattfolk** [comment]
A smaller example
```
start :: fn do
    [1, 2, 3] -> for_each(print)
end
```

**Comment by FredTheDino** [comment]
This is a fundamental problem with out type-checker. We discussed some design goals with Sylt - one of those was to deduce types where ever we could. I feel like these coincide, and my vote is there for to look into making an even better type-checker. (One that can reason between function boundaries)

I'm marking this as stale, and then I'm probably going to write a better type-checker.
