### ISSUE TITLE
Increase test-coverage

### ISSUE THREAD

**Issue by FredTheDino** [sylt-lang/sylt-lang#446]
It would be great if we had more test-coverage. It's just always a good idea. So more tests are always welcome.

Some places to start that might be easy-picking:

 - [ ] Tests for the std-lib - this will be great when we port to Lua
 - [ ] The `and` and `or` operators

Might be able to think of more if asked.

For more info: https://app.codecov.io/gh/FredTheDino/sylt-lang

**Comment by sornas** [comment]
Tests are added by writing sylt-code somewhere in the `tests`-directory. std-lib could have its own directory and `and`/`or` probably fits in `expression`.
