### ISSUE TITLE
standard library as importable modules

### ISSUE THREAD

**Issue by sornas** [sylt-lang/sylt-lang#506]
currently the entire standard library is included in the global namespace (terminology?). it should instead be in one (or multiple) module (-s) that can be imported. for example:

```
use std

start :: fn do
    numbers :: [1, 2, 3]
    numbers -> std.for_each' fn a: int do print(a) end
end
```

what to put where is a design debate to be had (with a lot of opinions, i think). i propose that the functionality itself is needed and the module design should be handled elsewhere.

we will also at least supply a löve-layer so some kind of functionality with multiple modules is needed.

**Comment by EMattfolk** [comment]
I feel like the standard library should be written in sylt if possible. We could at least set up the external things otherwise. Maybe #353 is back on the table? Glob imports?

**Comment by sornas** [comment]
Even with the standard library in sylt we still need to pass it to programs in some way. I don't think we want to distribute it together with each game separately.

**Comment by FredTheDino** [comment]
This is a thing since a while back - closing!
