### ISSUE TITLE
Global Names are not unique

### ISSUE THREAD

**Issue by EMattfolk** [sylt-lang/sylt-lang#527]
This has some unintended consequences where use statements get overwritten by the dependency checker. It may also affect external variables.

**Comment by sornas** [comment]
code example?

**Comment by EMattfolk** [comment]
> code example?

See the access_chain test. For some reason it did not fail before, but that was probably undefined behaviour.

**Comment by EMattfolk** [comment]
#528 Somewhat fixes this. I still think it may cause errors in the future, so this issue should stay open.

**Comment by FredTheDino** [comment]
Unsure what this is about anymore. The access_chain test looks to be working - so closing this unless someone has a better example.

**Comment by EMattfolk** [comment]
I suppose this was fixed when we refactored out `Name` in the compiler. :shrug:
