### ISSUE TITLE
Assume deduce type on arguments where `: Ty` is ommitted

### ISSUE THREAD

**Issue by FredTheDino** [sylt-lang/sylt-lang#534]
This should compile and work:
```
f :: fn a -> *
	a
end
```

Maybe only `do` implies void return type and `->`

**Comment by EMattfolk** [comment]
It is possible to implement this partially for only the function parameters. That should be quite easy.

**Comment by sornas** [comment]
Closed in #542

**Comment by FredTheDino** [comment]
It's already done
