### ISSUE TITLE
Enums!

### ISSUE THREAD

**Issue by FredTheDino** [sylt-lang/sylt-lang#559]
Some simple kind of enumeration:
```
Abc :: enum
	A,
	B int,
	C int,
end
```
And then some way to unpack them, maybe:
```
case a do
	A | 1
	B x | x + 2
	C x | x + 3
end
```

**Comment by EMattfolk** [comment]
```
case a do
    A -> 1
    B 1 -> 2
    C x -> x
    _ -> 0
end

case a do
    A => 1
    B 1 => 2
    C x => x
    _ => 0
end
```
I think an arrow makes the most sense.
Not sure about the enum declaration. We would have to think about how blobs will work in the future, and what about type aliases? Is this
```
Abc :: enum A, B int, C int end
```
ok?

Maybe something like:
```
Abc :: A
    | B int
    | C int
```
Now that unions are gone :crab:
