### ISSUE TITLE
Case statements

### ISSUE THREAD

**Issue by FredTheDino** [sylt-lang/sylt-lang#571]
Only works for variants - and requires something for all different variants.
Maybe something like this:
```
case Ab.A 1 do
	A x do
		ret x + 1
	end
	else do
		ret 2
	end
end
```
?

**Comment by sornas** [comment]
the double `do` feels a bit much to me but i realize that that's how our scopes look.

what about an additional case expression? where the case "block" has to be just a single expression and thus doesn't need a `do`/`end`.

```
// statement
case Ab.A 1 do
  Ab.A x do
    ret x + 1
  end
  else do
    ret 2
  end
end

// expression
ret case Ab.A 1 do // possibly something other than `do` so the parser knows the difference between statement and expression
  Ab.A x -> x + 1
  else -> 2
end
```
