### ISSUE TITLE
Move to if-expressions

### ISSUE THREAD

**Issue by FredTheDino** [sylt-lang/sylt-lang#573]
Promote if-statements to be if-expressions!

**Comment by FredTheDino** [comment]
This is currently impossible to do in a good way. (A good way is a way that works for all programs) It is currently not possible to write the lua-compiler without a large amount of hassle. Consider this code:
```
start :: fn ->
	print' 1 + if true do ret 4 else 5 end
end
```
When running this code, we wouldn't expect an output. But the lua-code I could generate would look like this:
```
function start()
	print' a + (function() if true do ret 4 else ret 5)()
end
```
So returns wouldn't work in if-statements, not good enough. Since functions cannot return to outer functions, so we cannot use a function.

But you think to yourself - surely this has to be possible! We're just not thinking hard enough, here's another example without functions:
```
function start()
	print' a + (function() if true do ret 4 else ret 5)()
end
```

**Comment by sornas** [comment]
sounds like an intermediate representation then. i havent thought about it specifically but it might be worth to check if there are any other changes we could make to the bytecode to make something else easier.

**Comment by sornas** [comment]
that is to say, maybe calling the bytecode an IR is a better mental model than "we have two compile targets but one depends on the other". and then remove the bytecode from the cli.
