### ISSUE TITLE
`+=` fails when compiling to lua

### ISSUE THREAD

**Issue by FredTheDino** [sylt-lang/sylt-lang#577]
```
a += "abc"
```
Since we translate `a += b` to `a = a + b`  which should be: `a = __ADD(a, b)`.
Only affects lua.

**Comment by FredTheDino** [comment]
I don't agree with this title change - did you test this? @sornas 

Because from what I could tell, it's ONLY `+=` with strings. If you found another bug can you elaborate on it?

**Comment by sornas** [comment]
no i just assumed. feel free to change to something more correct. (the old name was too general though)
