### ISSUE TITLE
Typechecker bug? from import use blob

### ISSUE THREAD

**Issue by Quaqqer** [sylt-lang/sylt-lang#595]
Importing Blobs with `from <import> use <blob>` causes an error, I assume that this is a bug. I provided some example test cases below. `from_use_blob.sy` does not work while `use_blob.sy` works. The error that `from_use_blob.sy` outputs is the following:

```
typecheck error: from_use_blob.sy:4
      Cannot resolve name 'Bob'
      Expected a blob or an enum
   2 | 
   3 | start :: fn do
   4 |     bob := Bob {
                  ^^^
```

https://github.com/sylt-lang/sylt-lang/compare/main...Quaqqer:blob-the-builder

**Comment by EMattfolk** [comment]
Nice find! I will check it out. Hopefully it is just some small thing we missed.

**Comment by EMattfolk** [comment]
It does indeed look like something we missed. Maybe you want to fix it?
Look at line 662 it the typechecker. There the blobs, enums and namespaces are ignored. The fix would be initializing them similar to the other match branches in `outer_statement`. You could cram in some more tests as well.
