### ISSUE TITLE
Unreachable case-branches should be error?

### ISSUE THREAD

**Issue by Quaqqer** [sylt-lang/sylt-lang#603]
This compiles, but it shouldn't.

```
Enum :: enum
    A,
end

start :: fn do
    a := Enum.A
    case a do
        B do
            print' "Hello there"
        end
        else do end
    end
end
```

**Comment by FredTheDino** [comment]
This looks correct - this doesn't make sense if you remove the `else` though.
#614 solves this
```
typecheck error: a.sy:7
      Enum 'Enum' lacks these variants:
       - B

   5 | start :: fn do
   6 |     a := Enum.A
   7 |     case a do
           ^^^^
help:
      Requirement came from
   5 | start :: fn do
   6 |     a := Enum.A
   7 |     case a do
           ^^^^

Error: "1 errors occured."
```

**Comment by EMattfolk** [comment]
This is apparently not fixed.

**Comment by FredTheDino** [comment]
First of all, we probably want to reason about this program:
```js
Enum :: enum
    A,
end

start :: fn do
    case Enum.A do
    	A do
            print' "a"
    	end
        B do
            print' "b"
        end
    end
end

```

This is more of a philosophical debate, of what you want the code to do. Either we accept this as okay, which I kinda did when I linked this, or we redefine the behavior, I see 2 options here:
 - *We report this as an error*, this is what most functional languages I know would do (except maybe Elixir). This would add stricter requirements to our case-s and thus we'd be more stringent with the different branches.
 - *We accept this*, if you don't want the flexibility don't add the else. This makes the function more general and it accepts anything you throw at it that might pass.
 
This is a double-edged sword, we get more generality and you can morph enums if the variants have the same names. It provides less safety for typos and the like, but in my opinion the `else` already throws out the window.

So where do we live, do people have opinions? I'm leaning towards allowing this and seeing what happens. The change is however trivial to make so either way is okay by me. But I am intrigued by the flexibility we can get from the `enum-morphing`.

**Comment by FredTheDino** [comment]
Unless anyone else has opinions here I'm gonna close this issue.

@EMattfolk  @Quaqqer

**Comment by EMattfolk** [comment]
I think it should be an error. It is too easy to make spelling mistakes otherwise. Also, I don't see the added flexibility being that useful. Maybe there are some cases I have not thought about.

**Comment by FredTheDino** [comment]
Well - we're making all enum-types open-types. Anyone can make their own implementation of `Maybe` which will just work. This could give us some extra flexability in the standard-library, forexample:
```
Maybe :: enum
	Some *a,
	None
end

Result :: enum
	Some *a,
	Error *b,
end
```
This lets us write code like:
```
unwrapOr :: fn x, default ->
	case x do
		Some x -> ret x
		else ret default
	end
end
```
This unwrap would work for both Result and Maybe, and if you want to introduce a third kind here, it would work flawlessly with the standardlibrary. This is just one small example.

**Comment by FredTheDino** [comment]
We decided to not allow unreachable branches.
