### ISSUE TITLE
Defining variables with same name as other in namespace causes error

### ISSUE THREAD

**Issue by Quaqqer** [sylt-lang/sylt-lang#604]
`test1.sy`
```
a :: fn -> float do
    ret .5
end
```

`test2.sy`
```
use test1

start :: fn do
    a := test1.a'
    b := test1.a'
end
```

Error caused:
```
typecheck error: test2.sy:5
      Got 'float', which it cannot be
      Not callable
   3 | start :: fn do
   4 |     a := test1.a'
   5 |     b := test1.a'
                       ^
```

**Comment by EMattfolk** [comment]
I tried finding the bug, but I still don't know what causes it. We should probably try to fix this by adding the compilation step where all namespaces are abstracted away.

**Comment by FredTheDino** [comment]
Do you have time to fix that extra compilation step? I think the earlier we get it in, the better.
