### ISSUE TITLE
Tuples in sets (and dicts probably)

### ISSUE THREAD

**Issue by EMattfolk** [sylt-lang/sylt-lang#606]
```
start :: fn do
    ((1,2) in {(1,2)}) <=> true
end
```
In lua all tuples are fundamentaly different when inserting into tables. Can we overwrite the hash function?

**Comment by EMattfolk** [comment]
Enums too.

**Comment by FredTheDino** [comment]
So this looks to be quite complicated... We will most likely need to write our own implementation where we hash stuff and put it in a list. But that also sounds sloooooow :(((((

**Comment by FredTheDino** [comment]
Fixed in #695

**Comment by FredTheDino** [comment]
> could we implement such things in rust and link using mlua? still a bit of overhead but maybe less than writing a hashing algorithm plain lua.

I don't think the overhead would be that insane, but I think it's more work for little gain. Lua has a hash-table built in, we could lean on it quite hard TBH. And we'd have to manage this seperate Rust dependency and distribute it with our program. Doesn't sound like the fastest or easiest way forward.
