### ISSUE TITLE
Int division is not implemented

### ISSUE THREAD

**Issue by EMattfolk** [sylt-lang/sylt-lang#632]
```
from std use print

start :: fn do
    a :: 1
    b: int = a / 2
    print(b)
end
```

**Comment by FredTheDino** [comment]
I'm thinking we should add a function or syntax for this?
Some suggestions are:
 - `\`
 - div-function

Unfortunately we cannot use "//", since it means comment. I feel like "//" makes a lot more sense though, and is easier to read and write, but idk.
