### ISSUE TITLE
`do` should force `void`

### ISSUE THREAD

**Issue by FredTheDino** [sylt-lang/sylt-lang#681]
Not related to this pr, but...

Isn't this a bit weird. The function is declared with `f :: fn a do` and not `f :: fn a ->`, and since there is no need for the ret keyword you cannot know at a glance if the function actually returns something. Take this for instance:

```
g :: fn do
    1
end

f :: fn do
    g'
end

start :: fn do
    print' f'
end
```

If you look at the definition of `f` there is no clear indication that it actually returns a value rather than void.

Maybe beginning a function with `do` should mark it as void?

_Originally posted by @Quaqqer in https://github.com/sylt-lang/sylt-lang/pull/680#discussion_r802512507_

**Comment by Quaqqer** [comment]
Something to note is that if `do` implies void return there is no way to do implicit return types on a single line, right? Ex. `fn x -> x * 2 end` shouldn't work, right?
